In [1]:
import numpy as np

In [2]:
arr = np.array([3,4,5,6,7])
squared = arr**2
print(squared)

[ 9 16 25 36 49]


In [3]:
arr + 10

array([13, 14, 15, 16, 17])

In [4]:
arr1 = np.array(([[1,2,3],[4,5,6],[7,8,9]]))
arr2 = np.array([1,2,3])
result = arr1 + arr2
print(result)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
