In [1]:
import numpy as np

In [2]:
arr = np.array([1,3,4,5])
print(arr)

[1 3 4 5]


In [3]:
np.zeros((3,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.arange(0,101,10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [10]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [13]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
myarr.shape

(4, 3)

In [16]:
myarr.size

12

In [17]:
myarr.ndim

2

In [18]:
myarr.dtype

dtype('int64')

In [21]:
d = myarr.astype('float64')
d.dtype

dtype('float64')

In [22]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
myarr.shape

(4, 3)

In [23]:
reshaped = myarr.reshape((3,4))
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
reshaped = myarr.reshape((2,6))
reshaped

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [24]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
flatenned = myarr.flatten()
flatenned

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])