In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
flat = arr.flatten()
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
flat[3]

np.int64(4)

In [5]:
flat[0]

np.int64(1)

In [6]:
flat[3:6]

array([4, 5, 6])

In [7]:
flat[:6]

array([1, 2, 3, 4, 5, 6])

In [8]:
b = flat[3:7]
b

array([4, 5, 6, 7])

In [9]:
b[0] = 45
b

array([45,  5,  6,  7])

In [10]:
flat

array([ 1,  2,  3, 45,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
b = flat[3:7].copy() #this will not make changes in the original array


In [11]:
arr = np.array((4,5,77,5,33,7))
arr[[1,2,5]]

array([ 5, 77,  7])

In [12]:
arr[arr>5]

array([77, 33,  7])