In [4]:
# python zip
l1 = [3,4,5]
l2 = [6,7,8]
l3 = [8,9,1]
list(zip(l1,l2,l3))

[(3, 6, 8), (4, 7, 9), (5, 8, 1)]

In [1]:
# using lists
import numpy as np
import time

size = 1_000_000
l1 = list(range(size))
l2 = list(range(size))

start = time.time()
add = [x+y for x,y in zip(l1,l2)]
end = time.time()
print(add[0:10])
print(end - start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0.03491997718811035


In [2]:
# using numpy arrays
import numpy as np
import time

size = 1_000_000
l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))

start = time.time()
add = l1 + l2
end = time.time()
print(add[0:10])
print(end - start)

[ 0  2  4  6  8 10 12 14 16 18]
0.00706791877746582


In [14]:
a1 = np.array([2,4,5,6,7])

print(a1.shape)

(5,)


In [7]:
a = np.array([[3,5,6],[4,6,4]])
print(a)

[[3 5 6]
 [4 6 4]]


In [8]:
type(a)

numpy.ndarray

In [11]:
a.shape

(2, 3)